services:
    chris1278.snowfall.listener:
        class: chris1278\snowfall\event\listener
        arguments:
            - '@auth'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
